// ignore_for_file: constant_identifier_names, non_constant_identifier_names

class PARAMS {
  static const int INT_TEXT_LIMIT_ADDRESS = 75;
  static const int RESULT_SUCCESS = 200,
      RESULT_NO_DATA_FOUND = 402,
      RESULT_NO_MORE_DATA_FOUND = 202,
      RESULT_REMOVE_CART = 306,
      RESULT_TOKAN_MISMATCH = 401;

  static const String PARAM_AUTHORIZATION = "Authorization";

  // Registration & Login
  static const String PARAM_FIRSTNAME = 'firstName',
      PARAM_LASTNAME = 'lastName',
      PARAM_EMAIL = 'email',
      PARAM_DATA = 'data',
      PARAM_COUNTRY = 'country',
      PARAM_PHONE = 'phone',
      PARAM_PASSWORD_CONFIRM = 'passwordConfirm',
      PARAM_INVITE = 'invite',
      PARAM_HEAREDABOUTUS = 'hearedAboutUs',
      PARAM_COUNTRY_CODE = 'countryCode',
      PARAM_COUNTRY_FLAG_CODE = 'countryFlagCode',
      PARAM_FIREBASE_TOKEN = 'firebaseToken',
      PARAM_PASSWORD = 'password',
      PARAM_NEWPASSWORD = 'newpassword';

  static const String PARAM_SOURCE = 'source',
      PARAM_DATE = 'date',
      PARAM_TIME = 'time',
      PARAM_LATITUDE = 'latitude',
      PARAM_LONGITUDE = 'longitude',
      PARAM_CUTOMERNOTE = 'cutomerNote',
      PARAM_ADDRESS = 'address',
      PARAM_IMAGE = 'image',
      PARAM_VOICE_NOTE = 'voice_note',
      PARAM_VIDEO = 'video';

  // update Profile
  static const String
      // PARAM_FIRSTNAME = 'firstName',
      // PARAM_LASTNAME = 'lastName',
      // PARAM_PHONE = 'phone',
      PARAM_EMERGENCYNAME = 'emergencyName',
      PARAM_EMERGENCYPHONE = 'emergencyPhone',
      PARAM_COUNTRYCODE = 'countryCode',
      PARAM_BRAND = 'brand',
      PARAM_COLOR = 'color',
      PARAM_MODELYEAR = 'modelYear',
      PARAM_MILEAGE = 'mileage',
      PARAM_SCANDRIVINGLISCENCE = 'scanDrivingLiscence',
      PARAM_SCANEMIRATESBACK = 'scanEmiratesBack',
      PARAM_SCANEMIRATESFRONT = 'scanEmiratesFront',
      PARAM_SCANMULKIA = 'scanMulkia';

  // cancle booking
  static const String PARAM_BOOKINGID = 'bookingId', PARAM_REASON = 'reason';

  //Update Profile
  static const int INT_LIMIT = 20;
  static const String PARAM_START = "start";
  static const String PARAM_LIMIT = "limit";

  static const String PARAM_ACTION = 'action',
      PARAM_USERNAME = 'userName',
      PARAM_USERPHONE = 'userPhone',
      PARAM_USEREMAILID = 'userEmailId',
      PARAM_ORDERID = 'orderId',
      PARAM_REASONDETAILS = 'reasonDetails',
      PARAM_HELPCOMMENTS = 'helpComments',
      PARAM_DEVICEINFO = 'deviceInfo';
}

class Constants {
  static const stripeKey =
      "sk_test_51L9OUFHYMywy7Uqrni2FavQa5IFG6tEvBuyfyV7VERpAzd8bULaGx27aDGDdz1hVkfwqY91KNdVxJt1C1PkBN2H800tyq9c8P2";
  static const stripePublishKey =
      "pk_test_51L9OUFHYMywy7UqrbREXzmBj470OQskl4oqvdbc4YLsrU5L96GVEOMTKTP2zAl8P5QC8OF2j9mnLv5SsGJPEQgRa00Py746Mtn";
  static const String APP_NAME = "Otobucks";
  static String strTokenType = "Bearer";
  static String STATUS = "STATUS";
  static String STR_GOOGLE_API_KEY = 'AIzaSyAP_6eekLauLbXqRjwncBDUtIfVCzoWGyA';

  static const String STR_PLATFORM_ANDROID = "Android",
      STR_PLATFORM_IOS = "IOS";

  static const String STR_APP_URL_ANDROID =
          "https://play.google.com/store/apps/details?id=com.otobucks.app",
      STR_APP_URL_IOS =
          "https://itunes.apple.com/in/app/whatsapp-messenger/id310633997?mt=8";

  static const String STRING_MMMM_yyyy = 'MMMM yyyy',
      STRING_DB_DATE_FORMATE = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
      STRING_DD_MMM_YYYY = 'dd MMM yyyy',
      STRING_YYYY_MM_DD = 'yyyy-MM-dd',
      STRING_DD_MMM_YY = 'dd MMM yy',
      STRING_DD_MM_YYYY_AA = 'dd-MM-yyyy hh:mm aa',
      STRING_DD_MMM_YYYY_AA = 'MMM dd, yyyy hh:mm aa',
      STRING_DD_MMM_YYYY_N = 'MMM dd, yyyy',
      STRING_EEEE_DD_MMM_YYYY = 'EEE, dd MMM yyyy';

  static const String MOBILE_REGX = "^[0-9]{6}",
      PASSWORD_REGX = "(?=.*\\d)(?=.*[A-Z]).{8,}",
      // ignore: prefer_adjacent_string_concatenation
      EMAIL_REGX =
          "[a-zA-Z0-9\\+\\.\\_\\%\\-\\+]{1,256}\\@[a-zA-Z0-9][a-zA-Z0-9\\-]{0,64}(\\.[a-zA-Z0-9][a-zA-Z0-9\\-]{0,25})+";

  static const String TAG_HOME = "Home",
      TAG_MY_PROFILE = 'My Profile',
      TAG_BOOKING_HISTORY = 'Booking History',
      TAG_PURCHASE_PRODUCT_HISTORY = 'Purchase Product History',
      TAG_NOTIFICATION = 'Notification',
      TAG_INBOX = 'Inbox',
      TAG_TRANSACTION_HISTORY = 'Transaction History',
      TAG_ANALYTICS = 'Analytics',
      TAG_CUSTOMER = 'Customer Support',
      TAG_WALLET = 'Wallet',
      TAG_INVITE_EARN = 'Invite & earn',
      TAG_RATINGS = 'Ratings',
      TAG_TERMS_CONDITIONS = 'Terms & Conditions',
      TAG_ABOUT_US = 'About Us',
      TAG_ENTER_YOUR_CAR_DETAILS = 'Enter your car details',
      TAG_ESTIMATION = 'Estimation',
      TAG_LOG_OUT = 'Log Out';

  // dashboard
  static const String STATUS_PENDING = "pending",
      STATUS_SUBMITTED = "submitted",
      STATUS_IN_PROGRESS = "in progress",
      STATUS_COMPLETED = "completed",
      STATUS_CANCELLED = "cancelled";

  // dashboard
  static const String TXT_VIEW_MORE = "View More",
      TXT_COMPLETED = "Completed",
      TXT_COMPLETED_ESTIMATION = "Complete Estimation",
      TXT_REBOOK_ESTIMATION = "Rebook",
      TXT_MAKE_A_PAYMENT = "Make a payment";

  // Profile

  static const String TAG_LOGIN = 'Login',
      TAG_SIGN_UP_TO_START = 'Sign up to Start',
      TAG_FORGOT_PASSWORD = 'Forgot password';

  // Wallet
  static const String TXT_ADD_MONEY = 'ADD Money',
      TXT_TOTAL_WALLET_BALANCE = 'Total Wallet Balance',
      TXT_CARDS = 'Cards',
      TXT_ADD_NEW_CARD = 'ADD NEW CARD',
      TXT_ALERT = 'ALERT!',
      TXT_DELETE_CARD = 'Delete Card',
      TXT_DELETE_CARD_MSG = 'Are you sure you wan’t to delete your card',
      TXT_WITHDRAW_OPTION_TEXT = 'Withdraw',
      TXT_ADD_ACC_OPTION_TEXT = 'Add account',
      TXT_WITHDRAW_MONEY_OPTION =
          'Would you like to withdraw money or add a bank accont first?',
      TXT_EDIT_CARD = 'EDIT CARD',
      TXT_TOTAL_EARNINGS = 'Total Earnings',
      TXT_TOTAL_WITHDRAWALS = 'Total withdrawals',
      TXT_CURRENT_BALANCE = 'Current Balance',
      TXT_WITHDRAW_MONEY = 'Withdraw money',
      TXT_WITHDRAW_HISTORY = 'Withdraw History',
      TXT_CARD_HOLDER_NAME = 'Card holder name',
      TXT_CARD_NUMBER = 'Card number',
      TXT_EXPIRY_DATE = 'Expiry date',
      TXT_CVV = 'Cvv',
      TXT_PROCEES_TO_PAY = 'Proceed to pay',
      TXT_SAVE_CARD = 'Save the card for further transactions',
      TXT_WALLET_EARNING_HISTORY = 'Wallet Earning History',
      // Bank details
      TXT_ADD_NEW_BANK = 'ADD NEW BANK',
      TXT_BANK_NAME = 'Bank Name',
      TXT_BANK_NAME_HINT = 'Enter Bank Name',
      TXT_ACCOUNT_HOLDER_NAME = 'Account holder name',
      TXT_ACCOUNT_HOLDER_NAME_HINT = 'Enter Account holder name',
      TXT_ACCOUNT_NUMBER = 'Account number',
      TXT_IBAN_NUMBER = 'Iban number',
      TXT_SWIFT_CODE = 'Swift Code',
      TXT_SWIFT_CODE_HINT = 'Enter Swift Code',
      TXT_BRANCH_NAME = 'Branch name',
      TXT_BRANCH_NAME_HINT = 'Enter Branch name',
      TXT_ROUTING = 'Routing Number',
      TXT_ROUTING_HINT = 'Enter Routing Number',
      TXT_ACCOUNT_TYPE = 'Account Type',
      TXT_ACCOUNT_TYPE_HINT = 'Enter Account Type',

      //Withdraw money
      TXT_VERIFY = 'Let’s verify it’s you',
      TXT_VERIFY_MSG =
          'Enter your verification code so we can make sure it’s you',
      TXT_VERIFY_MSG_3 =
          'Please enter the verification code we sent to your phone number ',
      TXT_VERIFY_DETAILS = 'Please review your withdrawal details.',
      TXT_TRANSFER_TO = 'Transfer to.';

  // Analytics

  static const String TXT_MY_EARNINGS = 'My earnings',
      TXT_BUY_PRODUCTS = 'Buy Products',
      TXT_VIEW_ALL = 'View All',
      TXT_TOTAL_INVITE_PEOPLES = 'Total Invite peoples',
      TXT_TOTAL_BUY_PRODUCTS = 'Total Buy Products';

  static const String TXT_SHARE_WITH_YOUR_FRIENDS = "Share with your friends:";
  static const String TXT_USERNAME_EMAIL = "Username or email address",
      TXT_NAME = "Enter Your Name",
      TXT_ENTER_NAME = "Enter Name",
      TXT_STATUS = "Status",
      TXT_SEARCH_BY_PRICE = "Search by Price",
      TXT_SEARCH_BY_DATE = "Search by Date",
      TXT_EMAIL_ID = "Email ID",
      TXT_PASSWORD = "Password",
      TXT_INVITE_FRIENDS = "Invite Friends",
      TXT_INVITED_FRIENDS = "Invited Friends",
      TXT_SEARCH = "Search",
      TXT_ONE_TIME_PASSWORD = "One time password",
      TXT_FORGOT_PASSWORD = "Forgot Password?",
      TXT_OR_LOGIN_WITH = "Or Login with",
      TXT_OR = "Or",
      TXT_DONT_HAVE_AN_AC = "Don’t have an account?",
      TXT_CREATE_AC = "Create Account",
      TXT_ALREADY_HAVE_AN_AC = "Already Have Account?",
      TXT_OTP_VERIFICATION = "OTP Verification",
      TXT_NEW_PASSWORD = "New Password",
      TXT_DIDNT_RECEIVE_THE_OTP = "Didn't receive the OTP?",
      TXT_ENTER_OTP = "Enter OTP",
      TXT_OTP_MSG2 =
          'We have sent you access code via SMS for mobile number verification.',
      TXT_OTP_MSG = 'We have sent you access code via E-Mail for verification.',
      TXT_LOGIN = "LOGIN",
      TXT_DOWNLOAD = "Download",
      TXT_LOGIN_SMALL = "Login",
      TXT_REGISTER = "REGISTER",
      TXT_TRANSACTION_DETAIL = "Transaction Detail",
      TXT_FACEBOOK = "Facebook",
      TXT_GOOGLE = "Google",
      TXT_SAVE_AND_PROCEED = "SAVE AND PROCEED",
      TXT_ADD_NEW = "Add New",
      TXT_UPDATE_DETAILS = "UPDATE DETAILS",
      TXT_PROFILE = "Profile",
      TXT_VIEW_BOOKING = "View Booking",
      TXT_CHAT_NOW = "Chat Now",
      TXT_WRITE_A_MESSAGE = "Write a message...",
      TXT_RATE_THIS_SERVICE = "Rate this service",
      TXT_REBOOK = "Rebook",
      TXT_SUBMIT = "SUBMIT",
      TXT_CONFIRM_WITHDRAW = "Confirm & withdraw",
      TXT_SAVE = "Save",
      TXT_BOOK_NOW = "Book Now",
      TXT_RESCHEDULE = "Reschedule",
      TXT_CANCEL_BOOKING = "Cancel Booking",
      TXT_CANCEL_BOOKING_REASON = "Reason for cancel booking",
      TXT_CANCEL_ESTIMATION_REASON = "Reason for decline estimation",
      TXT_ENTER_REASON = "enter your reason",
      TXT_CANCEL = "Cancel",
      TXT_DECLINE = "Decline",
      TXT_REQUEST_ESTIMATION = "Request Estimation",
      TXT_ALREADY_HAVE_ACCOUNT = 'Already have an account?',
      TXT_I_ACCEPT_THE = "I accept the ",
      TXT_FORGOT_PASS_MSG =
          'We just need your registered email-id to send you password reset instructions.',
      TXT_SIGN_UP = 'SIGN UP',
      TXT_ENT_CODE_MSG = "enter_code";

  static const String TXT_FLAT_NO = "HOUSE / FLAT NO.",
      TXT_LANDMARK = "LANDMARK",
      TXT_LOCATION = "Location - ",
      TXT_DELIVERING_TO = "Delivering to - ",
      TXT_CHECKOUT = "CHECKOUT",
      TXT_PAY_NOW = "PAY NOW",
      TXT_CHANGE = "Change",
      TXT_SAVE_AS = "SAVE AS";

  late double mLastClickTime, mClickTime = 1500.0;

  static const String TXT_FOOD = 'Food',
      TXT_GROCERIES = 'Groceries',
      TXT_VEGETABLES = 'Vegetables',
      TXT_STORE = 'Store';

  // for sqlite database
  static const String
      //device type
      DEVICE_TYPE = "Android",

      /*status true/false*/
      STATUS_TRUE = "True",
      STATUS_FALSE = "False";

  //  <!--Currency symbol-->
  static const String SYMBOL_RUPEE = "₹",
      SYMBOL_DOLLAR = "\$",
      SYMBOL_CDOLLAR = "CA\$",
      SYMBOL_EURO = "\u20ac",
      SYMBOL_POUND = "£",
      SYMBOL_YEN = "¥",
      SYMBOL_LIRA = "₤",
      SYMBOL_PESO = "₱",
      SYMBOL_FRF = "₣",
      SYMBOL_NLG = "U+0192",
      SYMBOL_DZD = "د.ج.‏",
      SYMBOL_RUR = "\u20BD‏",
      SYMBOL_MXP = "Mex\$‏",
      SYMBOL_CHF = "CHF",
      SYMBOL_ATS = "öS";

  //

  static const String TXT_PLEASE_WAIT = "Please wait compressing video";
  static const String TXT_CUSTOMER_ESTIMATION = "Customer Estimation",
      TXT_TAX_INVOICE = "Tax Invoice",
      TXT_DOWNLOAD_INVOICE = "Download Invoice",
      TXT_CUSTOMER_NAME = "Customer name:  ",
      TXT_DISCRIPTION = "Discription",
      TXT_INVOICE_ID = "Invoice ID:  ",
      TXT_INVOICE_DATE = "Invoice Date:  ",
      TXT_TITLE = "Title",
      TXT_QTY = "Qty",
      TXT_PRICE = "Price",
      TXT_START_DATE_END_DATE = "Start Date - End Date",
      TXT_AMOUNT = "Amount",
      TXT_SUB_TOTAL = "Sub Total",
      TXT_TOTAL = "Total",
      TXT_DISCOUNT = "Discount",
      TXT_THANKS_CONNECTING = "Thanks for Connecting with us";

  static const int INTENT_CAT_DETAILS = 100,
      INTENT_PRODUCT_DETAILS = 105,
      INTENT_BUSINESS_DETAILS = 106,
      INTENT_CONTACT_DETAILS = 109,
      INTENT_FINISH_ACT = 256,
      REQUEST_PERMISSION_SETTING = 101,
      REQUEST_APP_SETTING = 168,
      REQUEST_UPDATE_APP_ACTIVITY = 108;

  static const bool FLAG_DIALOG_APP_UPDATE = false;

  static const String RES_RESULT = "result";
  static const String RES_STATUS = "status";
  static const String RES_ERROR = "error";
  static const String RES_MESSAGE = "message";

  // for login
  static const String RES_TOKEN = "token";

  // exit app dialog
  static const String TEXT_EXIT = "Are you sure?",
      TEXT_EXIT_MSG = "Are you sure you want to exit ?",
      TEXT_YES = "Yes",
      TEXT_CANCEL = "Cancel",
      TEXT_NO = "No";

  static const String TEXT_DELETE = "Delete";

  static const String TAG_ACTIVE = 'Active';

  // app update Dialog

  static const String KEY_UPDATE_APP = "Update",
      KEY_NO_THANKS = "No,Thanks",
      KEY_APP_UPDATE_TITLE = "New Update available!",
      KEY_APP_UPDATE_MESSAGE =
          "A new version is available, Please update your app to new version.",
      RES_NO_DATA_FOUND = "no data found";

  // activity Name
  static const String ACT_HOME = '/HomeScreen';
  static const String ACT_HOME_WITH_THANKS = '/HomeScreenWithThanks';
  static const String ACT_SIGNUP = '/SignUp';
  static const String ACT_LOGIN = '/LoginPage';

  // static const String STRING_DD_MMM_YYYY = 'dd MMM yyyy',
  //     STRING_EEEE_DD_MMM_YYYY_AA = 'EEEE, dd MMM yyyy KK:mm aa';

  //County list
  static const String RES_DIAL_CODE = "dial_code",
      RES_NAME = "name",
      RES_CODE = "code";

  static const String CONTRY_CODE_BASE64 =
      "Ww0KICB7DQogICAgIm5hbWUiOiAiSW5kaWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzkxIiwNCiAgICAiY29kZSI6ICJJTiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlVuaXRlZCBLaW5nZG9tIiwNCiAgICAiZGlhbF9jb2RlIjogIis0NCIsDQogICAgImNvZGUiOiAiR0IiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJVbml0ZWQgU3RhdGVzIiwNCiAgICAiZGlhbF9jb2RlIjogIisxIiwNCiAgICAiY29kZSI6ICJVUyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkF1c3RyYWxpYSIsDQogICAgImRpYWxfY29kZSI6ICIrNjEiLA0KICAgICJjb2RlIjogIkFVIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ2FuYWRhIiwNCiAgICAiZGlhbF9jb2RlIjogIisxIiwNCiAgICAiY29kZSI6ICJDQSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk5ldyBDYWxlZG9uaWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzY4NyIsDQogICAgImNvZGUiOiAiTkMiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJBZmdoYW5pc3RhbiIsDQogICAgImRpYWxfY29kZSI6ICIrOTMiLA0KICAgICJjb2RlIjogIkFGIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQWxiYW5pYSIsDQogICAgImRpYWxfY29kZSI6ICIrMzU1IiwNCiAgICAiY29kZSI6ICJBTCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkFsZ2VyaWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzIxMyIsDQogICAgImNvZGUiOiAiRFoiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJBbWVyaWNhblNhbW9hIiwNCiAgICAiZGlhbF9jb2RlIjogIisxIiwNCiAgICAiY29kZSI6ICJBUyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkFuZG9ycmEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzM3NiIsDQogICAgImNvZGUiOiAiQUQiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJBbmdvbGEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzI0NCIsDQogICAgImNvZGUiOiAiQU8iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJBbmd1aWxsYSIsDQogICAgImRpYWxfY29kZSI6ICIrMSIsDQogICAgImNvZGUiOiAiQUkiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJBbnRhcmN0aWNhIiwNCiAgICAiZGlhbF9jb2RlIjogIis2NzIiLA0KICAgICJjb2RlIjogIkFRIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQW50aWd1YSBhbmQgQmFyYnVkYSIsDQogICAgImRpYWxfY29kZSI6ICIrMSIsDQogICAgImNvZGUiOiAiQUciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJBcmdlbnRpbmEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzU0IiwNCiAgICAiY29kZSI6ICJBUiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkFybWVuaWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzM3NCIsDQogICAgImNvZGUiOiAiQU0iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJBcnViYSIsDQogICAgImRpYWxfY29kZSI6ICIrMjk3IiwNCiAgICAiY29kZSI6ICJBVyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkF1c3RyaWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzQzIiwNCiAgICAiY29kZSI6ICJBVCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkF6ZXJiYWlqYW4iLA0KICAgICJkaWFsX2NvZGUiOiAiKzk5NCIsDQogICAgImNvZGUiOiAiQVoiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJCYWhhbWFzIiwNCiAgICAiZGlhbF9jb2RlIjogIisxIiwNCiAgICAiY29kZSI6ICJCUyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkJhaHJhaW4iLA0KICAgICJkaWFsX2NvZGUiOiAiKzk3MyIsDQogICAgImNvZGUiOiAiQkgiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJCYW5nbGFkZXNoIiwNCiAgICAiZGlhbF9jb2RlIjogIis4ODAiLA0KICAgICJjb2RlIjogIkJEIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQmFyYmFkb3MiLA0KICAgICJkaWFsX2NvZGUiOiAiKzEiLA0KICAgICJjb2RlIjogIkJCIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQmVsYXJ1cyIsDQogICAgImRpYWxfY29kZSI6ICIrMzc1IiwNCiAgICAiY29kZSI6ICJCWSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkJlbGdpdW0iLA0KICAgICJkaWFsX2NvZGUiOiAiKzMyIiwNCiAgICAiY29kZSI6ICJCRSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkJlbGl6ZSIsDQogICAgImRpYWxfY29kZSI6ICIrNTAxIiwNCiAgICAiY29kZSI6ICJCWiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkJlbmluIiwNCiAgICAiZGlhbF9jb2RlIjogIisyMjkiLA0KICAgICJjb2RlIjogIkJKIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQmVybXVkYSIsDQogICAgImRpYWxfY29kZSI6ICIrMSIsDQogICAgImNvZGUiOiAiQk0iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJCaHV0YW4iLA0KICAgICJkaWFsX2NvZGUiOiAiKzk3NSIsDQogICAgImNvZGUiOiAiQlQiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJCb2xpdmlhLCBQbHVyaW5hdGlvbmFsIFN0YXRlIG9mIiwNCiAgICAiZGlhbF9jb2RlIjogIis1OTEiLA0KICAgICJjb2RlIjogIkJPIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQm9zbmlhIGFuZCBIZXJ6ZWdvdmluYSIsDQogICAgImRpYWxfY29kZSI6ICIrMzg3IiwNCiAgICAiY29kZSI6ICJCQSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkJvdHN3YW5hIiwNCiAgICAiZGlhbF9jb2RlIjogIisyNjciLA0KICAgICJjb2RlIjogIkJXIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQnJhemlsIiwNCiAgICAiZGlhbF9jb2RlIjogIis1NSIsDQogICAgImNvZGUiOiAiQlIiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJCcml0aXNoIEluZGlhbiBPY2VhbiBUZXJyaXRvcnkiLA0KICAgICJkaWFsX2NvZGUiOiAiKzI0NiIsDQogICAgImNvZGUiOiAiSU8iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJCcnVuZWkgRGFydXNzYWxhbSIsDQogICAgImRpYWxfY29kZSI6ICIrNjczIiwNCiAgICAiY29kZSI6ICJCTiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkJ1bGdhcmlhIiwNCiAgICAiZGlhbF9jb2RlIjogIiszNTkiLA0KICAgICJjb2RlIjogIkJHIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQnVya2luYSBGYXNvIiwNCiAgICAiZGlhbF9jb2RlIjogIisyMjYiLA0KICAgICJjb2RlIjogIkJGIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQnVydW5kaSIsDQogICAgImRpYWxfY29kZSI6ICIrMjU3IiwNCiAgICAiY29kZSI6ICJCSSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkNhbWJvZGlhIiwNCiAgICAiZGlhbF9jb2RlIjogIis4NTUiLA0KICAgICJjb2RlIjogIktIIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ2FtZXJvb24iLA0KICAgICJkaWFsX2NvZGUiOiAiKzIzNyIsDQogICAgImNvZGUiOiAiQ00iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJDYXBlIFZlcmRlIiwNCiAgICAiZGlhbF9jb2RlIjogIisyMzgiLA0KICAgICJjb2RlIjogIkNWIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ2F5bWFuIElzbGFuZHMiLA0KICAgICJkaWFsX2NvZGUiOiAiKyAzNDUiLA0KICAgICJjb2RlIjogIktZIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ2VudHJhbCBBZnJpY2FuIFJlcHVibGljIiwNCiAgICAiZGlhbF9jb2RlIjogIisyMzYiLA0KICAgICJjb2RlIjogIkNGIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ2hhZCIsDQogICAgImRpYWxfY29kZSI6ICIrMjM1IiwNCiAgICAiY29kZSI6ICJURCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkNoaWxlIiwNCiAgICAiZGlhbF9jb2RlIjogIis1NiIsDQogICAgImNvZGUiOiAiQ0wiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJDaGluYSIsDQogICAgImRpYWxfY29kZSI6ICIrODYiLA0KICAgICJjb2RlIjogIkNOIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ2hyaXN0bWFzIElzbGFuZCIsDQogICAgImRpYWxfY29kZSI6ICIrNjEiLA0KICAgICJjb2RlIjogIkNYIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ29jb3MgKEtlZWxpbmcpIElzbGFuZHMiLA0KICAgICJkaWFsX2NvZGUiOiAiKzYxIiwNCiAgICAiY29kZSI6ICJDQyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkNvbG9tYmlhIiwNCiAgICAiZGlhbF9jb2RlIjogIis1NyIsDQogICAgImNvZGUiOiAiQ08iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJDb21vcm9zIiwNCiAgICAiZGlhbF9jb2RlIjogIisyNjkiLA0KICAgICJjb2RlIjogIktNIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ29uZ28iLA0KICAgICJkaWFsX2NvZGUiOiAiKzI0MiIsDQogICAgImNvZGUiOiAiQ0ciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJDb25nbywgVGhlIERlbW9jcmF0aWMgUmVwdWJsaWMgb2YgdGhlIiwNCiAgICAiZGlhbF9jb2RlIjogIisyNDMiLA0KICAgICJjb2RlIjogIkNEIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ29vayBJc2xhbmRzIiwNCiAgICAiZGlhbF9jb2RlIjogIis2ODIiLA0KICAgICJjb2RlIjogIkNLIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ29zdGEgUmljYSIsDQogICAgImRpYWxfY29kZSI6ICIrNTA2IiwNCiAgICAiY29kZSI6ICJDUiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkNvdGUgZCdJdm9pcmUiLA0KICAgICJkaWFsX2NvZGUiOiAiKzIyNSIsDQogICAgImNvZGUiOiAiQ0kiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJDcm9hdGlhIiwNCiAgICAiZGlhbF9jb2RlIjogIiszODUiLA0KICAgICJjb2RlIjogIkhSIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ3ViYSIsDQogICAgImRpYWxfY29kZSI6ICIrNTMiLA0KICAgICJjb2RlIjogIkNVIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ3lwcnVzIiwNCiAgICAiZGlhbF9jb2RlIjogIiszNTciLA0KICAgICJjb2RlIjogIkNZIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiQ3plY2ggUmVwdWJsaWMiLA0KICAgICJkaWFsX2NvZGUiOiAiKzQyMCIsDQogICAgImNvZGUiOiAiQ1oiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJEZW5tYXJrIiwNCiAgICAiZGlhbF9jb2RlIjogIis0NSIsDQogICAgImNvZGUiOiAiREsiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJEamlib3V0aSIsDQogICAgImRpYWxfY29kZSI6ICIrMjUzIiwNCiAgICAiY29kZSI6ICJESiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkRvbWluaWNhIiwNCiAgICAiZGlhbF9jb2RlIjogIisxIiwNCiAgICAiY29kZSI6ICJETSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkRvbWluaWNhbiBSZXB1YmxpYyIsDQogICAgImRpYWxfY29kZSI6ICIrMSIsDQogICAgImNvZGUiOiAiRE8iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJFY3VhZG9yIiwNCiAgICAiZGlhbF9jb2RlIjogIis1OTMiLA0KICAgICJjb2RlIjogIkVDIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiRWd5cHQiLA0KICAgICJkaWFsX2NvZGUiOiAiKzIwIiwNCiAgICAiY29kZSI6ICJFRyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkVsIFNhbHZhZG9yIiwNCiAgICAiZGlhbF9jb2RlIjogIis1MDMiLA0KICAgICJjb2RlIjogIlNWIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiRXF1YXRvcmlhbCBHdWluZWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzI0MCIsDQogICAgImNvZGUiOiAiR1EiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJFcml0cmVhIiwNCiAgICAiZGlhbF9jb2RlIjogIisyOTEiLA0KICAgICJjb2RlIjogIkVSIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiRXN0b25pYSIsDQogICAgImRpYWxfY29kZSI6ICIrMzcyIiwNCiAgICAiY29kZSI6ICJFRSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkV0aGlvcGlhIiwNCiAgICAiZGlhbF9jb2RlIjogIisyNTEiLA0KICAgICJjb2RlIjogIkVUIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiRmFsa2xhbmQgSXNsYW5kcyAoTWFsdmluYXMpIiwNCiAgICAiZGlhbF9jb2RlIjogIis1MDAiLA0KICAgICJjb2RlIjogIkZLIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiRmFyb2UgSXNsYW5kcyIsDQogICAgImRpYWxfY29kZSI6ICIrMjk4IiwNCiAgICAiY29kZSI6ICJGTyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkZpamkiLA0KICAgICJkaWFsX2NvZGUiOiAiKzY3OSIsDQogICAgImNvZGUiOiAiRkoiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJGaW5sYW5kIiwNCiAgICAiZGlhbF9jb2RlIjogIiszNTgiLA0KICAgICJjb2RlIjogIkZJIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiRnJhbmNlIiwNCiAgICAiZGlhbF9jb2RlIjogIiszMyIsDQogICAgImNvZGUiOiAiRlIiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJGcmVuY2ggR3VpYW5hIiwNCiAgICAiZGlhbF9jb2RlIjogIis1OTQiLA0KICAgICJjb2RlIjogIkdGIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiRnJlbmNoIFBvbHluZXNpYSIsDQogICAgImRpYWxfY29kZSI6ICIrNjg5IiwNCiAgICAiY29kZSI6ICJQRiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkdhYm9uIiwNCiAgICAiZGlhbF9jb2RlIjogIisyNDEiLA0KICAgICJjb2RlIjogIkdBIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiR2FtYmlhIiwNCiAgICAiZGlhbF9jb2RlIjogIisyMjAiLA0KICAgICJjb2RlIjogIkdNIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiR2VvcmdpYSIsDQogICAgImRpYWxfY29kZSI6ICIrOTk1IiwNCiAgICAiY29kZSI6ICJHRSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkdlcm1hbnkiLA0KICAgICJkaWFsX2NvZGUiOiAiKzQ5IiwNCiAgICAiY29kZSI6ICJERSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkdoYW5hIiwNCiAgICAiZGlhbF9jb2RlIjogIisyMzMiLA0KICAgICJjb2RlIjogIkdIIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiR2licmFsdGFyIiwNCiAgICAiZGlhbF9jb2RlIjogIiszNTAiLA0KICAgICJjb2RlIjogIkdJIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiR3JlZWNlIiwNCiAgICAiZGlhbF9jb2RlIjogIiszMCIsDQogICAgImNvZGUiOiAiR1IiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJHcmVlbmxhbmQiLA0KICAgICJkaWFsX2NvZGUiOiAiKzI5OSIsDQogICAgImNvZGUiOiAiR0wiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJHcmVuYWRhIiwNCiAgICAiZGlhbF9jb2RlIjogIisxIiwNCiAgICAiY29kZSI6ICJHRCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkd1YWRlbG91cGUiLA0KICAgICJkaWFsX2NvZGUiOiAiKzU5MCIsDQogICAgImNvZGUiOiAiR1AiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJHdWFtIiwNCiAgICAiZGlhbF9jb2RlIjogIisxIiwNCiAgICAiY29kZSI6ICJHVSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkd1YXRlbWFsYSIsDQogICAgImRpYWxfY29kZSI6ICIrNTAyIiwNCiAgICAiY29kZSI6ICJHVCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkd1ZXJuc2V5IiwNCiAgICAiZGlhbF9jb2RlIjogIis0NCIsDQogICAgImNvZGUiOiAiR0ciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJHdWluZWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzIyNCIsDQogICAgImNvZGUiOiAiR04iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJHdWluZWEtQmlzc2F1IiwNCiAgICAiZGlhbF9jb2RlIjogIisyNDUiLA0KICAgICJjb2RlIjogIkdXIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiR3V5YW5hIiwNCiAgICAiZGlhbF9jb2RlIjogIis1OTUiLA0KICAgICJjb2RlIjogIkdZIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiSGFpdGkiLA0KICAgICJkaWFsX2NvZGUiOiAiKzUwOSIsDQogICAgImNvZGUiOiAiSFQiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJIb2x5IFNlZSAoVmF0aWNhbiBDaXR5IFN0YXRlKSIsDQogICAgImRpYWxfY29kZSI6ICIrMzc5IiwNCiAgICAiY29kZSI6ICJWQSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkhvbmR1cmFzIiwNCiAgICAiZGlhbF9jb2RlIjogIis1MDQiLA0KICAgICJjb2RlIjogIkhOIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiSG9uZyBLb25nIiwNCiAgICAiZGlhbF9jb2RlIjogIis4NTIiLA0KICAgICJjb2RlIjogIkhLIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiSHVuZ2FyeSIsDQogICAgImRpYWxfY29kZSI6ICIrMzYiLA0KICAgICJjb2RlIjogIkhVIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiSWNlbGFuZCIsDQogICAgImRpYWxfY29kZSI6ICIrMzU0IiwNCiAgICAiY29kZSI6ICJJUyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkluZG9uZXNpYSIsDQogICAgImRpYWxfY29kZSI6ICIrNjIiLA0KICAgICJjb2RlIjogIklEIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiSXJhbiwgSXNsYW1pYyBSZXB1YmxpYyBvZiIsDQogICAgImRpYWxfY29kZSI6ICIrOTgiLA0KICAgICJjb2RlIjogIklSIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiSXJhcSIsDQogICAgImRpYWxfY29kZSI6ICIrOTY0IiwNCiAgICAiY29kZSI6ICJJUSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIklyZWxhbmQiLA0KICAgICJkaWFsX2NvZGUiOiAiKzM1MyIsDQogICAgImNvZGUiOiAiSUUiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJJc2xlIG9mIE1hbiIsDQogICAgImRpYWxfY29kZSI6ICIrNDQiLA0KICAgICJjb2RlIjogIklNIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiSXNyYWVsIiwNCiAgICAiZGlhbF9jb2RlIjogIis5NzIiLA0KICAgICJjb2RlIjogIklMIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiSXRhbHkiLA0KICAgICJkaWFsX2NvZGUiOiAiKzM5IiwNCiAgICAiY29kZSI6ICJJVCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkphbWFpY2EiLA0KICAgICJkaWFsX2NvZGUiOiAiKzEiLA0KICAgICJjb2RlIjogIkpNIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiSmFwYW4iLA0KICAgICJkaWFsX2NvZGUiOiAiKzgxIiwNCiAgICAiY29kZSI6ICJKUCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkplcnNleSIsDQogICAgImRpYWxfY29kZSI6ICIrNDQiLA0KICAgICJjb2RlIjogIkpFIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiSm9yZGFuIiwNCiAgICAiZGlhbF9jb2RlIjogIis5NjIiLA0KICAgICJjb2RlIjogIkpPIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiS2F6YWtoc3RhbiIsDQogICAgImRpYWxfY29kZSI6ICIrNyIsDQogICAgImNvZGUiOiAiS1oiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJLZW55YSIsDQogICAgImRpYWxfY29kZSI6ICIrMjU0IiwNCiAgICAiY29kZSI6ICJLRSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIktpcmliYXRpIiwNCiAgICAiZGlhbF9jb2RlIjogIis2ODYiLA0KICAgICJjb2RlIjogIktJIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiS29yZWEsIERlbW9jcmF0aWMgUGVvcGxlJ3MgUmVwdWJsaWMgb2YiLA0KICAgICJkaWFsX2NvZGUiOiAiKzg1MCIsDQogICAgImNvZGUiOiAiS1AiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJLb3JlYSwgUmVwdWJsaWMgb2YiLA0KICAgICJkaWFsX2NvZGUiOiAiKzgyIiwNCiAgICAiY29kZSI6ICJLUiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkt1d2FpdCIsDQogICAgImRpYWxfY29kZSI6ICIrOTY1IiwNCiAgICAiY29kZSI6ICJLVyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkt5cmd5enN0YW4iLA0KICAgICJkaWFsX2NvZGUiOiAiKzk5NiIsDQogICAgImNvZGUiOiAiS0ciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJMYW8gUGVvcGxlJ3MgRGVtb2NyYXRpYyBSZXB1YmxpYyIsDQogICAgImRpYWxfY29kZSI6ICIrODU2IiwNCiAgICAiY29kZSI6ICJMQSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkxhdHZpYSIsDQogICAgImRpYWxfY29kZSI6ICIrMzcxIiwNCiAgICAiY29kZSI6ICJMViINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkxlYmFub24iLA0KICAgICJkaWFsX2NvZGUiOiAiKzk2MSIsDQogICAgImNvZGUiOiAiTEIiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJMZXNvdGhvIiwNCiAgICAiZGlhbF9jb2RlIjogIisyNjYiLA0KICAgICJjb2RlIjogIkxTIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiTGliZXJpYSIsDQogICAgImRpYWxfY29kZSI6ICIrMjMxIiwNCiAgICAiY29kZSI6ICJMUiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIkxpYnlhbiBBcmFiIEphbWFoaXJpeWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzIxOCIsDQogICAgImNvZGUiOiAiTFkiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJMaWVjaHRlbnN0ZWluIiwNCiAgICAiZGlhbF9jb2RlIjogIis0MjMiLA0KICAgICJjb2RlIjogIkxJIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiTGl0aHVhbmlhIiwNCiAgICAiZGlhbF9jb2RlIjogIiszNzAiLA0KICAgICJjb2RlIjogIkxUIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiTHV4ZW1ib3VyZyIsDQogICAgImRpYWxfY29kZSI6ICIrMzUyIiwNCiAgICAiY29kZSI6ICJMVSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1hY2FvIiwNCiAgICAiZGlhbF9jb2RlIjogIis4NTMiLA0KICAgICJjb2RlIjogIk1PIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiTWFjZWRvbmlhLCBUaGUgRm9ybWVyIFl1Z29zbGF2IFJlcHVibGljIG9mIiwNCiAgICAiZGlhbF9jb2RlIjogIiszODkiLA0KICAgICJjb2RlIjogIk1LIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiTWFkYWdhc2NhciIsDQogICAgImRpYWxfY29kZSI6ICIrMjYxIiwNCiAgICAiY29kZSI6ICJNRyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1hbGF3aSIsDQogICAgImRpYWxfY29kZSI6ICIrMjY1IiwNCiAgICAiY29kZSI6ICJNVyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1hbGF5c2lhIiwNCiAgICAiZGlhbF9jb2RlIjogIis2MCIsDQogICAgImNvZGUiOiAiTVkiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJNYWxkaXZlcyIsDQogICAgImRpYWxfY29kZSI6ICIrOTYwIiwNCiAgICAiY29kZSI6ICJNViINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1hbGkiLA0KICAgICJkaWFsX2NvZGUiOiAiKzIyMyIsDQogICAgImNvZGUiOiAiTUwiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJNYWx0YSIsDQogICAgImRpYWxfY29kZSI6ICIrMzU2IiwNCiAgICAiY29kZSI6ICJNVCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1hcnNoYWxsIElzbGFuZHMiLA0KICAgICJkaWFsX2NvZGUiOiAiKzY5MiIsDQogICAgImNvZGUiOiAiTUgiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJNYXJ0aW5pcXVlIiwNCiAgICAiZGlhbF9jb2RlIjogIis1OTYiLA0KICAgICJjb2RlIjogIk1RIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiTWF1cml0YW5pYSIsDQogICAgImRpYWxfY29kZSI6ICIrMjIyIiwNCiAgICAiY29kZSI6ICJNUiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1hdXJpdGl1cyIsDQogICAgImRpYWxfY29kZSI6ICIrMjMwIiwNCiAgICAiY29kZSI6ICJNVSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1heW90dGUiLA0KICAgICJkaWFsX2NvZGUiOiAiKzI2MiIsDQogICAgImNvZGUiOiAiWVQiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJNZXhpY28iLA0KICAgICJkaWFsX2NvZGUiOiAiKzUyIiwNCiAgICAiY29kZSI6ICJNWCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1pY3JvbmVzaWEsIEZlZGVyYXRlZCBTdGF0ZXMgb2YiLA0KICAgICJkaWFsX2NvZGUiOiAiKzY5MSIsDQogICAgImNvZGUiOiAiRk0iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJNb2xkb3ZhLCBSZXB1YmxpYyBvZiIsDQogICAgImRpYWxfY29kZSI6ICIrMzczIiwNCiAgICAiY29kZSI6ICJNRCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1vbmFjbyIsDQogICAgImRpYWxfY29kZSI6ICIrMzc3IiwNCiAgICAiY29kZSI6ICJNQyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1vbmdvbGlhIiwNCiAgICAiZGlhbF9jb2RlIjogIis5NzYiLA0KICAgICJjb2RlIjogIk1OIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiTW9udGVuZWdybyIsDQogICAgImRpYWxfY29kZSI6ICIrMzgyIiwNCiAgICAiY29kZSI6ICJNRSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1vbnRzZXJyYXQiLA0KICAgICJkaWFsX2NvZGUiOiAiKzEiLA0KICAgICJjb2RlIjogIk1TIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiTW9yb2NjbyIsDQogICAgImRpYWxfY29kZSI6ICIrMjEyIiwNCiAgICAiY29kZSI6ICJNQSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk1vemFtYmlxdWUiLA0KICAgICJkaWFsX2NvZGUiOiAiKzI1OCIsDQogICAgImNvZGUiOiAiTVoiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJNeWFubWFyIiwNCiAgICAiZGlhbF9jb2RlIjogIis5NSIsDQogICAgImNvZGUiOiAiTU0iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJOYW1pYmlhIiwNCiAgICAiZGlhbF9jb2RlIjogIisyNjQiLA0KICAgICJjb2RlIjogIk5BIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiTmF1cnUiLA0KICAgICJkaWFsX2NvZGUiOiAiKzY3NCIsDQogICAgImNvZGUiOiAiTlIiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJOZXBhbCIsDQogICAgImRpYWxfY29kZSI6ICIrOTc3IiwNCiAgICAiY29kZSI6ICJOUCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk5ldGhlcmxhbmRzIiwNCiAgICAiZGlhbF9jb2RlIjogIiszMSIsDQogICAgImNvZGUiOiAiTkwiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJOZXRoZXJsYW5kcyBBbnRpbGxlcyIsDQogICAgImRpYWxfY29kZSI6ICIrNTk5IiwNCiAgICAiY29kZSI6ICJBTiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk5ldyBaZWFsYW5kIiwNCiAgICAiZGlhbF9jb2RlIjogIis2NCIsDQogICAgImNvZGUiOiAiTloiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJOaWNhcmFndWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzUwNSIsDQogICAgImNvZGUiOiAiTkkiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJOaWdlciIsDQogICAgImRpYWxfY29kZSI6ICIrMjI3IiwNCiAgICAiY29kZSI6ICJORSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIk5pZ2VyaWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzIzNCIsDQogICAgImNvZGUiOiAiTkciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJOaXVlIiwNCiAgICAiZGlhbF9jb2RlIjogIis2ODMiLA0KICAgICJjb2RlIjogIk5VIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiTm9yZm9sayBJc2xhbmQiLA0KICAgICJkaWFsX2NvZGUiOiAiKzY3MiIsDQogICAgImNvZGUiOiAiTkYiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJOb3J0aGVybiBNYXJpYW5hIElzbGFuZHMiLA0KICAgICJkaWFsX2NvZGUiOiAiKzEiLA0KICAgICJjb2RlIjogIk1QIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiTm9yd2F5IiwNCiAgICAiZGlhbF9jb2RlIjogIis0NyIsDQogICAgImNvZGUiOiAiTk8iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJPbWFuIiwNCiAgICAiZGlhbF9jb2RlIjogIis5NjgiLA0KICAgICJjb2RlIjogIk9NIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiUGFraXN0YW4iLA0KICAgICJkaWFsX2NvZGUiOiAiKzkyIiwNCiAgICAiY29kZSI6ICJQSyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlBhbGF1IiwNCiAgICAiZGlhbF9jb2RlIjogIis2ODAiLA0KICAgICJjb2RlIjogIlBXIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiUGFsZXN0aW5pYW4gVGVycml0b3J5LCBPY2N1cGllZCIsDQogICAgImRpYWxfY29kZSI6ICIrOTcwIiwNCiAgICAiY29kZSI6ICJQUyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlBhbmFtYSIsDQogICAgImRpYWxfY29kZSI6ICIrNTA3IiwNCiAgICAiY29kZSI6ICJQQSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlBhcHVhIE5ldyBHdWluZWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzY3NSIsDQogICAgImNvZGUiOiAiUEciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJQYXJhZ3VheSIsDQogICAgImRpYWxfY29kZSI6ICIrNTk1IiwNCiAgICAiY29kZSI6ICJQWSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlBlcnUiLA0KICAgICJkaWFsX2NvZGUiOiAiKzUxIiwNCiAgICAiY29kZSI6ICJQRSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlBoaWxpcHBpbmVzIiwNCiAgICAiZGlhbF9jb2RlIjogIis2MyIsDQogICAgImNvZGUiOiAiUEgiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJQaXRjYWlybiIsDQogICAgImRpYWxfY29kZSI6ICIrODcyIiwNCiAgICAiY29kZSI6ICJQTiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlBvbGFuZCIsDQogICAgImRpYWxfY29kZSI6ICIrNDgiLA0KICAgICJjb2RlIjogIlBMIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiUG9ydHVnYWwiLA0KICAgICJkaWFsX2NvZGUiOiAiKzM1MSIsDQogICAgImNvZGUiOiAiUFQiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJQdWVydG8gUmljbyIsDQogICAgImRpYWxfY29kZSI6ICIrMSIsDQogICAgImNvZGUiOiAiUFIiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJRYXRhciIsDQogICAgImRpYWxfY29kZSI6ICIrOTc0IiwNCiAgICAiY29kZSI6ICJRQSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlJvbWFuaWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzQwIiwNCiAgICAiY29kZSI6ICJSTyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlJ1c3NpYSIsDQogICAgImRpYWxfY29kZSI6ICIrNyIsDQogICAgImNvZGUiOiAiUlUiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJSd2FuZGEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzI1MCIsDQogICAgImNvZGUiOiAiUlciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJSw6l1bmlvbiIsDQogICAgImRpYWxfY29kZSI6ICIrMjYyIiwNCiAgICAiY29kZSI6ICJSRSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlNhaW50IEJhcnRow6lsZW15IiwNCiAgICAiZGlhbF9jb2RlIjogIis1OTAiLA0KICAgICJjb2RlIjogIkJMIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU2FpbnQgSGVsZW5hLCBBc2NlbnNpb24gYW5kIFRyaXN0YW4gRGEgQ3VuaGEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzI5MCIsDQogICAgImNvZGUiOiAiU0giDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJTYWludCBLaXR0cyBhbmQgTmV2aXMiLA0KICAgICJkaWFsX2NvZGUiOiAiKzEiLA0KICAgICJjb2RlIjogIktOIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU2FpbnQgTHVjaWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzEiLA0KICAgICJjb2RlIjogIkxDIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU2FpbnQgTWFydGluIiwNCiAgICAiZGlhbF9jb2RlIjogIis1OTAiLA0KICAgICJjb2RlIjogIk1GIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU2FpbnQgUGllcnJlIGFuZCBNaXF1ZWxvbiIsDQogICAgImRpYWxfY29kZSI6ICIrNTA4IiwNCiAgICAiY29kZSI6ICJQTSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlNhaW50IFZpbmNlbnQgYW5kIHRoZSBHcmVuYWRpbmVzIiwNCiAgICAiZGlhbF9jb2RlIjogIisxIiwNCiAgICAiY29kZSI6ICJWQyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlNhbW9hIiwNCiAgICAiZGlhbF9jb2RlIjogIis2ODUiLA0KICAgICJjb2RlIjogIldTIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU2FuIE1hcmlubyIsDQogICAgImRpYWxfY29kZSI6ICIrMzc4IiwNCiAgICAiY29kZSI6ICJTTSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlNhbyBUb21lIGFuZCBQcmluY2lwZSIsDQogICAgImRpYWxfY29kZSI6ICIrMjM5IiwNCiAgICAiY29kZSI6ICJTVCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlNhdWRpIEFyYWJpYSIsDQogICAgImRpYWxfY29kZSI6ICIrOTY2IiwNCiAgICAiY29kZSI6ICJTQSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlNlbmVnYWwiLA0KICAgICJkaWFsX2NvZGUiOiAiKzIyMSIsDQogICAgImNvZGUiOiAiU04iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJTZXJiaWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzM4MSIsDQogICAgImNvZGUiOiAiUlMiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJTZXljaGVsbGVzIiwNCiAgICAiZGlhbF9jb2RlIjogIisyNDgiLA0KICAgICJjb2RlIjogIlNDIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU2llcnJhIExlb25lIiwNCiAgICAiZGlhbF9jb2RlIjogIisyMzIiLA0KICAgICJjb2RlIjogIlNMIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU2luZ2Fwb3JlIiwNCiAgICAiZGlhbF9jb2RlIjogIis2NSIsDQogICAgImNvZGUiOiAiU0ciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJTbG92YWtpYSIsDQogICAgImRpYWxfY29kZSI6ICIrNDIxIiwNCiAgICAiY29kZSI6ICJTSyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlNsb3ZlbmlhIiwNCiAgICAiZGlhbF9jb2RlIjogIiszODYiLA0KICAgICJjb2RlIjogIlNJIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU29sb21vbiBJc2xhbmRzIiwNCiAgICAiZGlhbF9jb2RlIjogIis2NzciLA0KICAgICJjb2RlIjogIlNCIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU29tYWxpYSIsDQogICAgImRpYWxfY29kZSI6ICIrMjUyIiwNCiAgICAiY29kZSI6ICJTTyINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlNvdXRoIEFmcmljYSIsDQogICAgImRpYWxfY29kZSI6ICIrMjciLA0KICAgICJjb2RlIjogIlpBIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU291dGggR2VvcmdpYSBhbmQgdGhlIFNvdXRoIFNhbmR3aWNoIElzbGFuZHMiLA0KICAgICJkaWFsX2NvZGUiOiAiKzUwMCIsDQogICAgImNvZGUiOiAiR1MiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJTcGFpbiIsDQogICAgImRpYWxfY29kZSI6ICIrMzQiLA0KICAgICJjb2RlIjogIkVTIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU3JpIExhbmthIiwNCiAgICAiZGlhbF9jb2RlIjogIis5NCIsDQogICAgImNvZGUiOiAiTEsiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJTdWRhbiIsDQogICAgImRpYWxfY29kZSI6ICIrMjQ5IiwNCiAgICAiY29kZSI6ICJTRCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlN1cmluYW1lIiwNCiAgICAiZGlhbF9jb2RlIjogIis1OTciLA0KICAgICJjb2RlIjogIlNSIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU3ZhbGJhcmQgYW5kIEphbiBNYXllbiIsDQogICAgImRpYWxfY29kZSI6ICIrNDciLA0KICAgICJjb2RlIjogIlNKIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU3dhemlsYW5kIiwNCiAgICAiZGlhbF9jb2RlIjogIisyNjgiLA0KICAgICJjb2RlIjogIlNaIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU3dlZGVuIiwNCiAgICAiZGlhbF9jb2RlIjogIis0NiIsDQogICAgImNvZGUiOiAiU0UiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJTd2l0emVybGFuZCIsDQogICAgImRpYWxfY29kZSI6ICIrNDEiLA0KICAgICJjb2RlIjogIkNIIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiU3lyaWFuIEFyYWIgUmVwdWJsaWMiLA0KICAgICJkaWFsX2NvZGUiOiAiKzk2MyIsDQogICAgImNvZGUiOiAiU1kiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJUYWl3YW4iLA0KICAgICJkaWFsX2NvZGUiOiAiKzg4NiIsDQogICAgImNvZGUiOiAiVFciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJUYWppa2lzdGFuIiwNCiAgICAiZGlhbF9jb2RlIjogIis5OTIiLA0KICAgICJjb2RlIjogIlRKIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiVGFuemFuaWEsIFVuaXRlZCBSZXB1YmxpYyBvZiIsDQogICAgImRpYWxfY29kZSI6ICIrMjU1IiwNCiAgICAiY29kZSI6ICJUWiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlRoYWlsYW5kIiwNCiAgICAiZGlhbF9jb2RlIjogIis2NiIsDQogICAgImNvZGUiOiAiVEgiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJUaW1vci1MZXN0ZSIsDQogICAgImRpYWxfY29kZSI6ICIrNjcwIiwNCiAgICAiY29kZSI6ICJUTCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlRvZ28iLA0KICAgICJkaWFsX2NvZGUiOiAiKzIyOCIsDQogICAgImNvZGUiOiAiVEciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJUb2tlbGF1IiwNCiAgICAiZGlhbF9jb2RlIjogIis2OTAiLA0KICAgICJjb2RlIjogIlRLIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiVG9uZ2EiLA0KICAgICJkaWFsX2NvZGUiOiAiKzY3NiIsDQogICAgImNvZGUiOiAiVE8iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJUcmluaWRhZCBhbmQgVG9iYWdvIiwNCiAgICAiZGlhbF9jb2RlIjogIisxIiwNCiAgICAiY29kZSI6ICJUVCINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlR1bmlzaWEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzIxNiIsDQogICAgImNvZGUiOiAiVE4iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJUdXJrZXkiLA0KICAgICJkaWFsX2NvZGUiOiAiKzkwIiwNCiAgICAiY29kZSI6ICJUUiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlR1cmttZW5pc3RhbiIsDQogICAgImRpYWxfY29kZSI6ICIrOTkzIiwNCiAgICAiY29kZSI6ICJUTSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlR1cmtzIGFuZCBDYWljb3MgSXNsYW5kcyIsDQogICAgImRpYWxfY29kZSI6ICIrMSIsDQogICAgImNvZGUiOiAiVEMiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJUdXZhbHUiLA0KICAgICJkaWFsX2NvZGUiOiAiKzY4OCIsDQogICAgImNvZGUiOiAiVFYiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJVZ2FuZGEiLA0KICAgICJkaWFsX2NvZGUiOiAiKzI1NiIsDQogICAgImNvZGUiOiAiVUciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJVa3JhaW5lIiwNCiAgICAiZGlhbF9jb2RlIjogIiszODAiLA0KICAgICJjb2RlIjogIlVBIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiVW5pdGVkIEFyYWIgRW1pcmF0ZXMiLA0KICAgICJkaWFsX2NvZGUiOiAiKzk3MSIsDQogICAgImNvZGUiOiAiQUUiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJVcnVndWF5IiwNCiAgICAiZGlhbF9jb2RlIjogIis1OTgiLA0KICAgICJjb2RlIjogIlVZIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiVXpiZWtpc3RhbiIsDQogICAgImRpYWxfY29kZSI6ICIrOTk4IiwNCiAgICAiY29kZSI6ICJVWiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlZhbnVhdHUiLA0KICAgICJkaWFsX2NvZGUiOiAiKzY3OCIsDQogICAgImNvZGUiOiAiVlUiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJWZW5lenVlbGEsIEJvbGl2YXJpYW4gUmVwdWJsaWMgb2YiLA0KICAgICJkaWFsX2NvZGUiOiAiKzU4IiwNCiAgICAiY29kZSI6ICJWRSINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlZpZXQgTmFtIiwNCiAgICAiZGlhbF9jb2RlIjogIis4NCIsDQogICAgImNvZGUiOiAiVk4iDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJWaXJnaW4gSXNsYW5kcywgQnJpdGlzaCIsDQogICAgImRpYWxfY29kZSI6ICIrMSIsDQogICAgImNvZGUiOiAiVkciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJWaXJnaW4gSXNsYW5kcywgVS5TLiIsDQogICAgImRpYWxfY29kZSI6ICIrMSIsDQogICAgImNvZGUiOiAiVkkiDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICJXYWxsaXMgYW5kIEZ1dHVuYSIsDQogICAgImRpYWxfY29kZSI6ICIrNjgxIiwNCiAgICAiY29kZSI6ICJXRiINCiAgfSwNCiAgew0KICAgICJuYW1lIjogIlllbWVuIiwNCiAgICAiZGlhbF9jb2RlIjogIis5NjciLA0KICAgICJjb2RlIjogIllFIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiWmFtYmlhIiwNCiAgICAiZGlhbF9jb2RlIjogIisyNjAiLA0KICAgICJjb2RlIjogIlpNIg0KICB9LA0KICB7DQogICAgIm5hbWUiOiAiWmltYmFid2UiLA0KICAgICJkaWFsX2NvZGUiOiAiKzI2MyIsDQogICAgImNvZGUiOiAiWlciDQogIH0sDQogIHsNCiAgICAibmFtZSI6ICLDhWxhbmQgSXNsYW5kcyIsDQogICAgImRpYWxfY29kZSI6ICIrMzU4IiwNCiAgICAiY29kZSI6ICJBWCINCiAgfQ0KXQ==";

  // Logout app dialog
  static const String STRING_SIGN_OUT = "Sign Out?",
      STRING_SIGN_OUT_MSG = "Do you want to Sign Out ?",
      STRING_OK = "Ok",
      STRING_BACK = "Back";

  static const String STRING_PRODUCT_QUANTITY = "Product Quantity",
      STRING_ORDER_DETAIL = "Order Detail",
      STRING_PRODUCT_DETAIL = "Product Detail",
      STRING_SUBSCRIBE = "Subscribe",
      STRING_SUBSCRIPTION_START_DATE = "Subscription Start & End Date",
      STRING_START_SUBSCRIPTION = "Start Subscription",
      STRING_PICK_SCHEDULE = "Pick Schedule",
      STRING_ORDER_DATE = "Order Date : ";

  // Image Selection Dilog
  static const String STRING_SORT_BY = "Sort By",
      STRING_ADD_PHOTO = "Choose Image!",
      STRING_CHOOSE_FROM_LIB = "Choose from Library",
      STRING_CAPTURE_PHOTO = "Capture photo",
      STRING_CANCEL = "Cancel";

  static const String STR_SIGN_IN = 'Sign In',
      STR_LOGOUT = 'Logout',
      STR_RESEND = 'Resend',
      STR_CONTINUE = 'Continue',
      STR_SELECT = 'Select',
      STR_UPDATE = 'Update';

  static const String STR_FIRST_NAME = 'First Name',
      STR_LAST_NAME = 'Last Name',
      STR_EMAIL = 'Email',
      STR_SEARCH = 'Search',
      STR_HOW_DID = 'How did you here about us',
      STR_COUNTRY = 'Country',
      STR_PASSWORD = 'Password',
      STR_CONTACT_PERSON = 'Contact Person',
      STR_MOBILE_NUMBER = 'Mobile Number',
      STR_CREATE_PASSWORD = 'Create Password',
      STR_CONFIRM_PASSWORD = 'Confirm Password',
      STR_INVITATION_CODE = 'Invitation Code',
      STR_OTP_CODE = 'OTP Code',
      STR_FORGOT_PASSWORD = 'Forgot Password';

  // Profile
  static const String STR_NAME = 'Name',
      STR_ADDRESS = 'Address',
      STR_ENTER_YOUR_CAR_DETAILS = 'Enter your car details',
      STR_EMERGENCY_CONTACT_DETAIL = 'Emergency Contact detail',
      STR_CAR_BRAND = 'Car brand',
      STR_CAR_MODEL_YEAR = 'Car model year',
      STR_MILEAGE = 'Milegae of car has gone',
      STR_CAR_COLOUR = 'Car Colour',
      STR_ADD_MULKIA = 'Add \n Mulkia',
      STR_ADD_DRIVING_LICENCE = 'Add \n Driving Licence',
      STR_ADD_EMIRATES_ID_FRONT = 'Add \n Emirates id front',
      STR_ADD_EMIRATES_ID_BACK = 'Add \n Emirates id back',
      STR_UPDATE_YOUR_PROFILE = 'Update your Profile';

  static const String STR_IMAGE_MSG = "Upload image or Take a photo";
  static const String STR_MAX_SIZE = "(Up to 10 mb)";
  static const String STR_VIDEO_MSG = "Upload Video or Shoot a video";
  static const String STR_LEAVE_NOTE = "Leave Note (if any)";
  static const String STR_LEAVE_VOICE_NOTE = "Leave voice note";
  static const String STR_LONG_PRESS_VOICE_NOTE =
      "Long press for make voice note.";
  static const String STR_NOTIFICATION = 'Notification';
  static const String STR_INBOX = 'Inbox';
  static const String STR_RESET = 'Reset', STR_APPLY = 'Apply';

  static String STRING_OTP_SENT = "OTP Succesfully Sent";
  static String STRING_OTP_FAILED = "OTP Sending Failed";
  static String STRING_OTP_SUCCESSFULLLY_SENT_FULL_ST =
      "Please check your phone for the verification code.";
}

class SharedPrefKey {
  static const String KEY_IS_LOGIN = "islogin",
      KEY_USER_ID = "id",
      KEY_FIRST_NAME = "first_name",
      KEY_LAST_NAME = "last_name",
      KEY_USER_IMAGE = "image",
      KEY_APP_LATITUDE = "latitude",
      KEY_APP_LONGITUDE = "longitude",
      KEY_KEY_MOBILE_NUMBER = "mobile_number",
      KEY_KEY_EMAIL = "email",
      KEY_CART_ITEM_COUNT = 'cart_item_count',
      KEY_CART_TOTAL_PRICE = 'cart_total_price',
      KEY_SELECTED_ADDRESS = 'selected_address',
      KEY_ACCESS_TOKEN = "strAccessToken",
      KEY_FIREBASE_TOKEN = "firebase_token",
      KEY_EMAIL_VERIFIED = "emailVerified";
}

class AppAlert {
  // add Edit Catalogue
  static const String ALERT = "Alert";
  static const String ALERT_SERVER_NOT_RESPONDING = "Internal server error.";
  static const String MSG_NO_RECORDS_FOUND = "No records found";
  static const String ALERT_NO_INTERNET_CONNECTION = "No Internet Connection.";
  static const String ALERT_PLEASE_TRY_AFTER_SOME_TIME =
      "Please try after some time.";

  // app update Dialog
  static const String ALERT_STRING_UPDATE_APP = "Update",
      STRING_NO_THANKS = "No,Thanks",
      STRING_APP_UPDATE_TITLE = "New Update available!",
      STRING_APP_UPDATE_MESSAGE =
          "A new version of ${Constants.APP_NAME} is available, Please update your app to new version.";

  //  Check out ALERT
  static const String ALERT_ENTER_NAME = "Please enter name.";

  static const String ALERT_ENTER_NUMBER = "Please enter mobile number.";
  static const String ALERT_ENTER_VALID_NUMBER =
      "Please enter valid mobile number.";

  static const String ALERT_ENTER_ADDRESS = "Please enter address.";
  static const String ALERT_ENTER_EMG_NAME = "Please enter emergency name.";
  static const String ALERT_ENTER_EMG_NUMBER =
      "Please enter emergency phone number.";
  static const String ALERT_ENTER_CAR_BRAND = "Please enter car brand.";
  static const String ALERT_ENTER_CAR_MODEL_YEAR =
      "Please enter car model year.";
  static const String ALERT_ENTER_CAR_MILAGE = "Please enter car milage.";
  static const String ALERT_TEXT_COPY = "Copied to clipboard";
  static const String ALERT_ENTER_CAR_COLOR = "Please enter car color.";
  static const String ALERT_ENTER_PHONE_NUMBER = "Please enter phone number.";
  static const String ALERT_SELECT_DATE = "Please select date.";
  static const String ALERT_SELECT_TIME = "Please select time.";
  static const String ALERT_ENTER_EMAIL = "Please enter Email.";
  static const String ALERT_ENTER_EMAIL_AND_PASSWORD =
      "Please enter Email and Password";
  static const String ALERT_ENTER_EMAIL_OR_PHONE =
      "Please enter Email or Phone No.";
  static const String ALERT_ENTER_FN = "Please enter First name.";
  static const String ALERT_ENTER_BANK_NAME = "Please enter Bank Name.";
  static const String ALERT_ENTER_AC_HOLDER_NAME =
      "Please enter Account holder name.";
  static const String ALERT_ENTER_AC_NUMBER = "Please enter Account number.";
  static const String ALERT_ENTER_IBAN_NUMBER = "Please enter Iban Number.";
  static const String ALERT_ENTER_SWIFT_CODE = "Please enter Swift code.";
  static const String ALERT_ENTER_BARNCH_NAME = "Please enter Branch name.";
  static const String ALERT_ENTER_RESON = "Please enter Reason.";
  static const String ALERT_ENTER_LN = "Please enter Last name.";
  static const String ALERT_SELECT_COUNTRY = "Please select Country.";
  static const String ALERT_ENTER_VALID_EMAIL = "Please enter valid Email.";
  static const String ALERT_ENTER_CARD_HOLDER_NAME =
      "Please Enter card holder name.";
  static const String ALERT_ENTER_CARD_NUMBER = "Please Enter card number.";
  static const String ALERT_ENTER_VALID_CARD_NUMBER =
      "Please Enter valid card number.";
  static const String ALERT_ENTER_CARD_EXPIRY =
      "Please Enter card expiry date.";
  static const String ALERT_ENTER_CARD_CVV = "Please Enter card cvv.";
  static const String ALERT_ENTER_VALID_CVV = "Please Enter valid cvv number.";

  static String STRING_ALLOW_LOCATION_ACCESS =
      'Please allow location access to move further';
  static const String ALERT_ENTER_PASSWORD = "Please enter password.";
  static const String ALERT_ENTER_VALID_PASSWORD =
      "Password must contain at least one uppercase letter,one lowercase letter and one special character.";
  static const String ALERT_ENTER_CONFIRM_PASSWORD =
      "Please enter confirm password.";
  static const String ALERT_PASSWORD_NOT_MATCH =
      "Please check password and confirm password are not matched.";
  static const String ALERT_ACCEPT_TERMS =
      "Please accept Terms and Conditions..";
  static const String ALERT_ENTER_CODE = "Please Enter Code";

  static const String ALERT_ENTER_OTP = "Please enter 6 digit OTP.";
  static const String ALERT_ENTER_VALID_OTP = "Please enter Valid OTP.";
  static const String ALERT_ENTER_ADDRESS_1 = "Please enter Address line 1.";
  static const String ALERT_ENTER_PINCODE = "Please enter Pincode.";
  static const String ALERT_ENTER_VALID_PINCODE = "Please enter valid Pincode.";
  static const String ALERT_ENTER_ADDRESS_2 = "Please enter Address line 2.";
  static const String ALERT_SELECT_STATE = "Please select State";
  static const String ALERT_SELECT_CITY = "Please select City";
  static const String ALERT_SELECT_ADDRESS_TYPE = "Please select Address type";
  static const String ALERT_SELECT_DOB = "Please select date of birth";
  static const String ALERT_GST_NUMBER = "Please enter GST Number.";
  static const String ALERT_ACCOUNT_HOLDER_NAME =
      "Please enter Account Holder Name.";
  static const String ALERT_GST_REGI_IMAGE =
      "Please upload GST Registration Image.";
  static const String ALERT_GST_DECLARATION_IMAGE =
      "Please upload GST Declaration Image.";
  static const String ALERT_CANCELLED_CHEQUE_IMAGE =
      "Please upload Cancelled Cheque Image.";
  static const String ALERT_PANCARD_IMAGE = "Please upload PanCard Image.";
  static const String ALERT_PLEASE_SELECT_FUTURE_TIME =
      "Please select a future time slot.";
  static const String ALERT_PLEASE_SELECT_FUTURE_DATE_AND_TIME =
      "Please select a future date for select time slot.";
  static const String ALERT_PLEASE_ACCEPT_TERMS =
      "Please accept Terms & Conditions";

  static const String ALERT_FILE_SIZE =
      "Please select video file less than 10 MB.";
  static const String ALERT_FILE_SIZE_ALL =
      "Please select file less than 10 MB.";

  static const String TEXT_EXIT = 'Are you sure?',
      STRING_CART_REMOVE_PRODUCT_MESSAGE =
          'Do you want to remove this product from cart.';
}
